In [2]:
import numpy as np

## NumPy array

The main object in NumPy is the multi-dimensional array data structure called `ndarray`, or simply as `array`. The `ndarray` data structure is different to Python standard list, tuple, or `array.array` object, since it offers a lot more functionality. The following notebook lists the more important concepts and functions involving `ndarray` that we are going to use in this course, so that you can quickly refer to it should you need to. For a more complete introduction to NumPy, please refer to the official quickstart page at https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html.

To simplify the discussion, we are going to refer to the `ndarray` object simply as array. 


### Array creation

Main reference: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.creation.html

There are two main methods of creating an array: we can convert a Python list or tuple into one, or we construct one from scratch using one of the array-creation function.

Conversion from other Python structures is straightforward:

In [16]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

Otherwise, we can use one of many array-creation functions, which are mostly self-explanatory:
* `ones([m,n])` - create an array of 1s
* `zeros([m,n])` - create an array of 0s
* `full([m,n], x)` - create an array filled with `x`
* `empty([m,n])` - create an array, but do not initialise the values (may contain garbage), but marginally faster

All of the above functions create an array with m rows and n columns. You can increase the dimension by adding more values in the list. For example:

In [29]:
a = np.zeros([2,2,3])
a

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

You can also specify the type using the `dtype` parameter:

In [30]:
a = np.full([2,3],5,dtype=np.complex64)
a

array([[5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j]], dtype=complex64)

The basic data types in NumPy can be found here: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html